//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Hall.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SKINTESTDLG_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_LOGIN                       129
#define IDD_DIALOG1                     132
#define IDD_LOBBY                       132
#define IDD_HALL                        132
#define IDI_ICON1                       133
#define IDI_TRAY1                       133
#define IDI_TRAY_LOGING                 133
#define IDR_MENU_TRAY                   134
#define IDD_SEARCH_DLG                  135
#define IDR_MENU_MYHEAD                 136
#define IDD_MSGBOX                      137
#define IDD_USER_DETAIL_INFO_DLG        138
#define IDD_CHANGEUSER_OR_EXIT          139
#define IDD_SYS_SETTING                 140
#define IDD_SHOW_PERSONAL_DLG           141
#define IDD_SHOW_AUDIO_VERIFY_DLG       142
#define IDD_SHOW_BASIC_SETTING_DLG      143
#define IDD_SHOW_AUDIO_SETTING_DLG      144
#define IDD_SHOW_HARASSMENT_DLG         145
#define IDD_SHOW_PWD_SAFE_DLG           146
#define IDD_SHOW_MYROOM_DLG             147
#define IDD_SAFE_BOX_DLG                148
#define IDD_SHOW_BALANCE_DLG            149
#define IDD_SHOW_DEPOSIT_DLG            150
#define IDD_SHOW_CHECK_AND_WITHDRAWING_DLG 151
#define IDD_CHANGE_LINE_DLG             152
#define IDD_AUDIO_DLG                   153
#define IDD_REGISTER_DLG                154
#define IDD_DIALOG2                     155
#define IDD_VERIFY                      155
#define IDD_DIALOG3                     156
#define IDD_SYSTEM_NOTIFY_DLG           156
#define IDI_TRAY_UPDATE3                158
#define IDD_ROOM_PASSWORD_DLG           162
#define IDD_DIALOG4                     163
#define IDD_ENTERING_ROOM_DLG           163
#define IDD_UPDATEGUIDE_DLG             167
#define IDD_DIALOG5                     168
#define IDD_OTHER_SYSNOTIFY_DLG         168
#define IDD_HEAD_SETTING_DLG            169
#define IDD_PIC_TRACKER_DLG             170
#define IDC_CURSOR1                     171
#define IDC_CURSOR2                     172
#define IDD_QQ_LOGIN_DLG                174
#define IDI_TIPS                        175
#define IDD_CHECK_UPDATE_DLG            176
#define IDD_SHOW_SOUND_SETTING_DLG      177
#define IDD_SHOW_MY_ACCOUNT_DLG         178
#define IDD_SHOW_MESSAGE_SETTING_DLG    179
#define IDD_AUDIOTEST_DLG               180
#define IDD_AUDIOTEST_STEP1             181
#define IDD_AUDIOTEST_STEP2             182
#define IDD_HALL_SYSNOTIFY_HTML_DLG     183
#define IDC_COMBO1                      1003
#define IDC_COMBO_AREA                  1003
#define IDC_COMBO_GENDER                1003
#define IDC_COMBO_CAMERA                1003
#define IDC_COMBO_MIC                   1003
#define IDC_COMBO_LOUDSPEAKER           1003
#define IDC_COMBO_ACCOUNT               1004
#define IDC_PASSWORD                    1005
#define IDC_CHECK1                      1006
#define IDC_CHECK2                      1007
#define IDC_ROOMLIST_BROWSER            1009
#define IDC_ALL_ROOM                    1010
#define IDC_EDIT1                       1011
#define IDC_EDIT_SEARCH                 1011
#define IDC_EDIT_USERACCOUNT            1011
#define IDC_EDIT_OLD_PWD                1011
#define IDC_EDIT_INPUT_DEPOSIT          1011
#define IDC_EDIT_INPUT_SECOND_PWD       1011
#define IDC_EDIT_VERIFY                 1011
#define IDC_EDIT_CODE                   1011
#define IDC_EDIT_ROOM_PWD               1011
#define IDC_EDIT_PASSWORD               1012
#define IDC_TREE_ROOMLIST               1012
#define IDC_ITEM_HTML                   1013
#define IDC_EDIT_USERNICKNAME           1014
#define IDC_COMBO_YEAR                  1015
#define IDC_COMBO_MONTH                 1016
#define IDC_COMBO_DATE                  1017
#define IDC_COMBO_CITY                  1018
#define IDC_COMBO_TOWN                  1019
#define IDC_HTML_AUDIO_VERIFY           1020
#define IDC_CHECK_OPENSOUND             1021
#define IDC_CHECK_AUTOLOGIN             1022
#define IDC_CHECK_AUTORUN               1023
#define IDC_HTML_MYROOM                 1024
#define IDC_RADIO_UPVIP                 1025
#define IDC_RADIO_HUANGGUAN             1026
#define IDC_RADIO_REFUSEANY             1027
#define IDC_RADIO_ONLY_FRIEND_INVITE    1028
#define IDC_RADIO_REFUSE_ANY_INVITE     1029
#define IDC_CHECK_MODIFY_PWD            1030
#define IDC_EDIT_NEW_PWD                1031
#define IDC_EDIT_CONFIRM_PWD            1032
#define IDC_EDIT_INPUT_MONEY            1033
#define IDC_RADIO_DIANXIN               1034
#define IDC_RADIO_WANGTONG              1035
#define IDC_HTML_REGISTER               1036
#define IDC_HTML_PWDSAFE                1037
#define IDC_TICKER_BOTTOM               1038
#define IDC_HTML_PERSONAL_INFO          1041
#define IDC_CHECK_AUTO_AUDIOPARTNER     1042
#define IDC_PASSWRONG                   1043
#define IDC_HTML_UPDATEGUIDE            1044
#define IDC_TRACKER_SLIDER              1045
#define IDC_HTML_QQ_LOGIN               1046
#define IDC_COMBO_ACCOUNT_TEST          1048
#define IDC_HTML_SHOW_MY_ACCOUNT        1049
#define IDC_RADIO_SING                  1050
#define IDC_RADIO_CHAT_WITH_PEOPLE      1051
#define IDC_RADIO_PLAY_SONG             1052
#define IDC_SLIDER_TOTAL_VOLUMN         1053
#define IDC_SLIDER_SONG_ACCOMPANY       1054
#define IDC_SLIDER_VOLUMN_MIC           1055
#define IDC_SLIDER_MIX                  1056
#define IDC_SLIDER_RECORD_MIC           1057
#define IDC_SLIDER_LOUDSPEAKER          1058
#define IDC_SLIDER_MICFONE              1059
#define IDC_RADIO_JUST_HIGHER_VIP       1060
#define IDC_RADIO_JUST_HIGHER_HUANGGUAN 1061
#define IDC_RADIO_REFUSE_ALL_PEOPLE     1062
#define IDC_CHECK_FORBID_GIFT_MSG       1063
#define IDC_CHECK_OPEN_SPEAKER_SCROLL   1064
#define IDC_CHECK_FORBID_BIG_GIFT_SHOW  1065
#define IDC_CHECK_FORBID_SPEAKER_SOUND  1066
#define IDC_CHECK_FORBID_PUBLIC_TALK    1067
#define IDC_CHECK_FORBID_PRIVATE_TALK   1068
#define IDC_CHECK_OPEN_MSG_SCROLL       1069
#define IDC_CHECK8                      1070
#define IDC_CHECK_FORBID_USER_IN_OUT    1070
#define IDC_HTML_SYSNOTIFY              1071
#define ID_32771                        32771
#define ID_                             32772
#define ID_TRAYMENU_HIDEWND             32773
#define ID_TRAYMENU_USERSETTING         32774
#define ID_TRAYMENU_VEDIOSETTING        32775
#define ID_TRAYMENU_HELP                32776
#define ID_TRAYMENU_ABOUT               32777
#define ID_TRAYMENU_CHANGEUSER          32778
#define ID_TRAYMENU_EXIT                32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
