####################################################################
#
# Makefile for fractional arithmetic library
# $Id: Makefile,v 1.7.2.3 2004-12-22 09:04:53 ehr Exp $
#
####################################################################
include make.cfg


################## user section: insert objlist here #######
LIB = libFloatFR.a


OBJS =	$(OBJDIR)/transcendent.o \
	$(OBJDIR)/cfftn.o


include stdtargets.cfg

DATE   :=$(shell date +%Y-%m-%d)
TARGET  = FloatFRlib
