#pragma once

#define WM_MYSELF_MESSAGE_BEGIN			WM_USER+1100
#define WM_PRIVATEMICDLG_CLOSE			WM_MYSELF_MESSAGE_BEGIN+1				//私聊对话框关闭
#define PUBLIC_TIMER					WM_MYSELF_MESSAGE_BEGIN+2				//排上公麦后,剩余时间提示

#define WM_CHANGEVIDEO					WM_MYSELF_MESSAGE_BEGIN+3				//关闭/开启视频
#define WM_CHANGEAUDIO					WM_MYSELF_MESSAGE_BEGIN+4				//关闭/开启音频
#define WM_CHANGESIZE					WM_MYSELF_MESSAGE_BEGIN+5				//改变视频窗口大小
#define WM_PHOTO						WM_MYSELF_MESSAGE_BEGIN+6				//拍照
#define WM_MICPOPUPDLG_CLOSE			WM_MYSELF_MESSAGE_BEGIN+7				//视频弹出框关闭
#define WM_P2PMICDLG_CLOSE				WM_MYSELF_MESSAGE_BEGIN+8				//一对一私聊对话框关闭

#define WM_CLICK_EMOTION				WM_MYSELF_MESSAGE_BEGIN+9				//点击标签框
#define WM_SEARCHEDIT_CHANGE			WM_MYSELF_MESSAGE_BEGIN+10				//用户列表搜索框文字改变
#define WM_SELFDEFINE_SHORTCUT			WM_MYSELF_MESSAGE_BEGIN+11				//自定义快捷短语
#define WM_CLICK_SHORTCUT				WM_MYSELF_MESSAGE_BEGIN+12				//点击快捷短语
#define WM_CLICK_GIFTLIST				WM_MYSELF_MESSAGE_BEGIN+13				//点击道具商城
#define WM_CLICK_STAMP					WM_MYSELF_MESSAGE_BEGIN+14				//点击弹出印章框
#define WM_CLICK_CAIZI					WM_MYSELF_MESSAGE_BEGIN+15				//点击彩条
#define WM_CLICK_USERLIST				WM_MYSELF_MESSAGE_BEGIN+16				//点击用户列表
#define WM_CLICK_SPEAKER				WM_MYSELF_MESSAGE_BEGIN+17				//点击小喇叭
#define WM_CLICK_WISHSONG				WM_MYSELF_MESSAGE_BEGIN+18				//点击祝福点歌
#define WM_CLICK_STAMPLIST				WM_MYSELF_MESSAGE_BEGIN+19				//点击选中印章
#define WM_CLICK_MYGOODSLIST			WM_MYSELF_MESSAGE_BEGIN+35				//点击选中包裹物品

#define PAODAO_MOVE_TIMER				WM_MYSELF_MESSAGE_BEGIN+20				//跑道区移到定时器
#define WM_CLICK_VIDEO_DLG				WM_MYSELF_MESSAGE_BEGIN+21				//点击视频窗口

#define PAODAO_DRAW_GIF_TIMER			WM_MYSELF_MESSAGE_BEGIN+29				//跑道区绘制gif定时器
#define PAODAO_DRAW_GIF_TIMER_INTERVAL	75
#define PAODAO_MOVE_SPEED				(PAODAO_DRAW_GIF_TIMER_INTERVAL*2/25)

#define WM_SHOW_GIFT_TIP				WM_MYSELF_MESSAGE_BEGIN+22				//显示礼物信息卡片
#define WM_CLICK_CHANGEVOICE			WM_MYSELF_MESSAGE_BEGIN+23				//点击弹出变声卡选择框
#define WM_CLICK_CHANGEVOICELIST		WM_MYSELF_MESSAGE_BEGIN+24				//点击选中变声卡
#define WM_CLICK_FLYINGTEXT				WM_MYSELF_MESSAGE_BEGIN+25				//点击弹出飞屏输入框
#define WM_CLICK_AUTOREPLY_MENU         WM_MYSELF_MESSAGE_BEGIN+26             //点击自动回复

#define WM_GUESTREGISTER_TIMER			WM_MYSELF_MESSAGE_BEGIN+27				//提示游客注册对话框时间到
#define WM_GUESTREGISTER_DLG_CLOSE		WM_MYSELF_MESSAGE_BEGIN+28				//提示游客注册对话框关闭

#define WM_DBCLICK_USERLIST				WM_MYSELF_MESSAGE_BEGIN+30				//双击用户列表
#define WM_CLICK_BUYSOFA				WM_MYSELF_MESSAGE_BEGIN+31				//用户点击沙发
#define WM_CLICK_FLASH					WM_MYSELF_MESSAGE_BEGIN+32				//用户点击flash
#define WM_CLICK_SOFA_NAME				WM_MYSELF_MESSAGE_BEGIN+33				//用户点击沙发用户昵称
#define WM_FLASH_KILLFOCUS				WM_MYSELF_MESSAGE_BEGIN+34				//flash失去焦点
