####################################################################
#
# Makefile for bit buffer management library
# $Id: Makefile,v 1.2.4.1 2004-02-03 17:40:04 ehr Exp $
#
####################################################################
include make.cfg


################## user section: insert objlist here #######
LIB = libbitbuf.a


OBJS =	$(OBJDIR)/bitbuffer.o

include stdtargets.cfg

DATE   :=$(shell date +%Y-%m-%d)
TARGET  = FloatFR_bitbuflib

